export const companies = [
  {
    id: 1,
    name: "Company A",
    cin: "CIN123456",
    panGst: "GST123456",
    contactPerson: "John Doe",
    email: "contact@companya.com",
    phone: "123-456-7890",
    address: "123 Company St, City, Country",
    website: "https://companya.com",
  },
  {
    id: 2,
    name: "Company B",
    cin: "CIN654321",
    panGst: "GST654321",
    contactPerson: "Jane Smith",
    email: "contact@companyb.com",
    phone: "123-456-7891",
    address: "456 Company Ave, City, Country",
    website: "https://companyb.com",
  },
  {
    id: 3,
    name: "Company C",
    cin: "CIN789012",
    panGst: "GST789012",
    contactPerson: "Alice Johnson",
    email: "contact@companyc.com",
    phone: "123-456-7892",
    address: "789 Company Blvd, City, Country",
    website: "https://companyc.com",
  },
  {
    id: 4,
    name: "Company D",
    cin: "CIN345678",
    panGst: "GST345678",
    contactPerson: "Bob Brown",
    email: "contact@companyd.com",
    phone: "123-456-7893",
    address: "321 Company Rd, City, Country",
    website: "https://companyd.com",
  },
];
