export const products = [
  {
    id: 1,
    name: "Image 1",
    description: "Description for Image 1",
    image: "4N5A1106.jpg",
    instock: false,
  },
  {
    id: 2,
    name: "Image 3",
    description: "Description for Image 3",
    image: "Set_squre_90deg.jpg",
    instock: true,
  },
  // {
  //   id: 3,
  //   name: "Image 4",
  //   description: "Description for Image 4",
  // image: "Set_squre_equ.jpg",
  //   instock: true,
  // },
  // {
  //   id: 4,
  //   name: "Image 6",
  //   description: "Description for Image 6",
  //   // image: "metal/4N5A1249.jpg",
  //   instock: false,
  // },
  // {
  //   id: 5,
  //   name: "Image 7",
  //   description: "Description for Image 7",
  //   // image: "metal/4N5A1268.jpg",
  //   instock: true,
  // },
  // {
  //   id: 6,
  //   name: "Image 8",
  //   description: "Description for Image 8",
  //   // image: "metal/4N5A1297.jpg",
  //   instock: false,
  // },
  // {
  //   id: 7,
  //   name: "Image 9",
  //   description: "Description for Image 9",
  //   image: "metal/4N5A1302.jpg",
  //   instock: true,
  // },
  // {
  //   id: 8,
  //   name: "Image 10",
  //   description: "Description for Image 10",
  //   // image: "metal/4N5A1306.jpg",
  //   instock: true,
  // },
  // {
  //   id: 9,
  //   name: "Image 11",
  //   description: "Description for Image 11",
  //   // image: "metal/4N5A1373.jpg",
  //   instock: true,
  // },
  {
    id: 10,
    name: "Image 12",
    description: "Description for Image 12",
    image: "metal/4N5A1385.jpg",
    instock: true,
  },
  // {
  //   id: 11,
  //   name: "Image 13",
  //   description: "Description for Image 13",
  //   // image: "metal/4N5A1446.jpg",
  //   instock: true,
  // },
  // {
  //   id: 12,
  //   name: "Image 14",
  //   description: "Description for Image 14",
  //   // image: "metal/Untitled-2.png",
  //   instock: true,
  // },
  {
    id: 13,
    name: "Image 15",
    description: "Description for Image 15",
    image: "metal/Untitled-3.png",
    instock: true,
  },
  // {
  //   id: 14,
  //   name: "Image 16",
  //   description: "Description for Image 16",
  //   // image: "metal/Untitled-256.png",
  //   instock: true,
  // },
  // {
  //   id: 15,
  //   name: "Image 17",
  //   description: "Description for Image 17",
  //   // image: "plastic/4N5A1105.jpg",
  //   instock: true,
  // },
  // {
  //   id: 16,
  //   name: "Image 18",
  //   description: "Description for Image 18",
  //   // image: "plastic/4N5A1113.jpg",
  //   instock: true,
  // },
  // {
  //   id: 17,
  //   name: "Image 19",
  //   description: "Description for Image 19",
  //   // image: "plastic/4N5A1121.jpg",
  //   instock: true,
  // },
  // {
  //   id: 18,
  //   name: "Image 20",
  //   description: "Description for Image 20",
  //   // image: "plastic/4N5A1126.jpg",
  //   instock: true,
  // },
  // {
  //   id: 19,
  //   name: "Image 21",
  //   description: "Description for Image 21",
  //   // image: "plastic/4N5A1130.jpg",
  //   instock: true,
  // },
  // {
  //   id: 20,
  //   name: "Image 22",
  //   description: "Description for Image 22",
  //   // image: "plastic/4N5A1132.jpg",
  //   instock: true,
  // },
  // {
  //   id: 21,
  //   name: "Image 23",
  //   description: "Description for Image 23",
  //   // image: "plastic/4N5A1145.jpg",
  //   instock: true,
  // },
  // {
  //   id: 22,
  //   name: "Image 24",
  //   description: "Description for Image 24",
  //   // image: "plastic/4N5A1154.jpg",
  //   instock: true,
  // },
  // {
  //   id: 23,
  //   name: "Image 25",
  //   description: "Description for Image 25",
  //   // image: "plastic/4N5A1160.jpg",
  //   instock: true,
  // },
  // {
  //   id: 24,
  //   name: "Image 26",
  //   description: "Description for Image 26",
  //   // image: "plastic/4N5A1163.jpg",
  //   instock: true,
  // },
  // {
  //   id: 25,
  //   name: "Image 27",
  //   description: "Description for Image 27",
  //   // image: "plastic/4N5A1174.jpg",
  //   instock: true,
  // },
  // {
  //   id: 26,
  //   name: "Image 28",
  //   description: "Description for Image 28",
  //   // image: "plastic/4N5A1176.jpg",
  //   instock: true,
  // },
  // {
  //   id: 27,
  //   name: "Image 29",
  //   description: "Description for Image 29",
  //   // image: "plastic/4N5A1180.jpg",
  //   instock: true,
  // },
  // {
  //   id: 28,
  //   name: "Image 30",
  //   description: "Description for Image 30",
  //   // image: "plastic/4N5A1184.jpg",
  //   instock: true,
  // },
  // {
  //   id: 29,
  //   name: "Image 31",
  //   description: "Description for Image 31",
  //   // image: "plastic/4N5A1189.jpg",
  //   instock: true,
  // },
  // {
  //   id: 30,
  //   name: "Image 32",
  //   description: "Description for Image 32",
  //   // image: "plastic/4N5A1191.jpg",
  //   instock: true,
  // },
  // {
  //   id: 31,
  //   name: "Image 33",
  //   description: "Description for Image 33",
  //   // image: "plastic/4N5A1198.jpg",
  //   instock: true,
  // },
  // {
  //   id: 32,
  //   name: "Image 34",
  //   description: "Description for Image 34",
  //   // image: "plastic/4N5A1202.jpg",
  //   instock: true,
  // },
  // {
  //   id: 33,
  //   name: "Image 35",
  //   description: "Description for Image 35",
  //   // image: "plastic/4N5A1207.jpg",
  //   instock: true,
  // },
  // {
  //   id: 34,
  //   name: "Image 36",
  //   description: "Description for Image 36",
  //   // image: "plastic/4N5A1209.jpg",
  //   instock: true,
  // },
  // {
  //   id: 35,
  //   name: "Image 37",
  //   description: "Description for Image 37",
  //   // image: "plastic/4N5A1219.jpg",
  //   instock: true,
  // },
  // {
  //   id: 36,
  //   name: "Image 38",
  //   description: "Description for Image 38",
  //   // image: "plastic/4N5A1223.jpg",
  //   instock: true,
  // },
  // {
  //   id: 37,
  //   name: "Image 39",
  //   description: "Description for Image 39",
  //   // image: "plastic/4N5A1236.jpg",
  //   instock: true,
  // },
  {
    id: 38,
    name: "Image 40",
    description: "Description for Image 40",
    image: "plastic/4N5A1440.jpg",
    instock: true,
  },
];
